version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.8"

mkdocs:
  configuration: .readthedocs.mkdocs.yaml
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt  # 确保路径正确
